name: ci

on: push

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        bun: [latest] # Mengganti matrix node dengan bun

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Saya sesuaikan ke v4 karena ini versi stabil terbaru

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun }}

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Typecheck
        run: bun run typecheck
